In [1]:
import numpy as np
import pandas as pd

scores = np.random.randint(50,101,size=(50,5))
scores_pd = pd.DataFrame(scores,
             columns=['國文','英文','數學','地理','歷史'],
             index = range(1,51)
             )
scores_pd

     國文   英文   數學  地理  歷史
1    61   75   61  66  83
2    50   83   53  69  69
3    95   80   60  68  69
4    76   74   99  71  61
5    99   61   71  66  86
6    53   74   60  62  68
7    75   53   80  98  71
8    69   94   83  94  98
9    65   77   84  91  65
10   52   78   77  52  69
11   59   98   93  98  54
12   50   94   99  68  76
13   90   63   78  79  52
14   57   90   72  77  55
15   72   58   74  58  71
16   78   83   75  86  65
17   64   71   82  88  78
18   82   56   86  95  87
19   92   58   93  66  84
20   81   86   61  74  65
21   78   81   71  58  71
22   94   61   57  71  54
23   82   65   54  90  54
24   79   77   97  70  82
25   71   56   56  94  90
26   65   57   91  91  67
27   54  100   68  65  97
28   71   98   87  79  57
29   55   85   64  61  95
30   68   73   82  76  79
31   87   89   95  86  74
32  100  100   68  97  79
33   88   87   70  89  73
34   96   52   87  84  95
35   98   90   98  69  52
36   73   96   88  86  72
37   85   99   78  74  71
38   54   51   58  87  93
39   85   57   67  84  56
40   57   70   53  74  57
41   66   74   52  80  93
42   55   78   78  94  78
43   76   74   63  85  98
44   79   51   61  50  89
45   76   79  100  52  96
46   76   56   64  81  68
47   68   91   52  99  52
48   78   87   73  68  82
49   59   86   70  93  92
50   75   96   68  89  71

In [8]:
def callback1(value:pd.Series):
    return pd.Series([value.max(),value.min(),value.median(),value.mean()],index=['最高分','最低分','中間值','平均值'])
    
dataFrama1 = scores_pd.apply(callback1)
dataFrama1

         國文      英文      數學     地理     歷史
最高分  100.00  100.00  100.00  99.00  98.00
最低分   50.00   51.00   52.00  50.00  52.00
中間值   75.00   77.50   72.50  79.00  71.50
平均值   73.36   76.44   74.22  78.04  74.26